export enum ApplicationStatus {
  PENDING = 'PENDING',
  REVIEW = 'REVIEW',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEWED = 'INTERVIEWED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  SUBMITTED = 'SUBMITTED'
}